name: Codeclimate coverage report

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Codeclimate coverage report
        uses: marsam/codeclimate-action@master
        with:
          command: jest --coverage --coverageReporters=lcov
          reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
